- hosts: localhost
  become: true
  gather_facts: false  
  name: Eth node setup
  tasks:
    - name: Creates directory 
      file:
        path: /opt/ethlight/
        state: directory       
    - name: Copy docker-compose files
      copy:
        src: "/home/ayush/ansible/eth/docker-compose.yml"
        dest: "/opt/ethlight/"
    - name: Start eth node using docker-compose up
      command:
        cmd:  docker-compose -f /opt/ethlight/docker-compose.yml up -d 

